// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSmNrAGwyGQ7O1zluDAEegb4cH8c0Z3cI',
    appId: '1:132090256520:web:d6575ea9d375c32c14d33d',
    messagingSenderId: '132090256520',
    projectId: 'demoproject-26253',
    authDomain: 'demoproject-26253.firebaseapp.com',
    storageBucket: 'demoproject-26253.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQCGYHl8PgDYtaQA5CAzyOF-TEdNtuku0',
    appId: '1:132090256520:android:51f0e404b71da5db14d33d',
    messagingSenderId: '132090256520',
    projectId: 'demoproject-26253',
    storageBucket: 'demoproject-26253.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyqc4lJbdcnQ984VXdAFTuWPlRBzUyuxc',
    appId: '1:132090256520:ios:add47dd921e944b814d33d',
    messagingSenderId: '132090256520',
    projectId: 'demoproject-26253',
    storageBucket: 'demoproject-26253.firebasestorage.app',
    iosBundleId: 'com.example.december',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyqc4lJbdcnQ984VXdAFTuWPlRBzUyuxc',
    appId: '1:132090256520:ios:add47dd921e944b814d33d',
    messagingSenderId: '132090256520',
    projectId: 'demoproject-26253',
    storageBucket: 'demoproject-26253.firebasestorage.app',
    iosBundleId: 'com.example.december',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSmNrAGwyGQ7O1zluDAEegb4cH8c0Z3cI',
    appId: '1:132090256520:web:19bdf834b59b4f0614d33d',
    messagingSenderId: '132090256520',
    projectId: 'demoproject-26253',
    authDomain: 'demoproject-26253.firebaseapp.com',
    storageBucket: 'demoproject-26253.firebasestorage.app',
  );
}
